import { Geometry, MeshPhongMaterial, Fog, Light, Vector3 } from 'three';
import Cell from '../grids/Cell';

export interface TileSettings {
  cell: Cell;
  geometry: Geometry;
  material?: MeshPhongMaterial;
  scale?: number;
};

export interface ExtrudeSettings {
  amount?: number;
  bevelEnabled?: boolean;
  bevelSegments?: number;
  steps?: number;
  bevelSize?: number;
  bevelThickness?: number;
};

export interface TilemapSettings {
  tileScale?: number;
  cellSize?: number;
  material?: MeshPhongMaterial;
  extrudeSettings?: ExtrudeSettings;
}

export interface GridSettings {
  cellSize?: number;
  size?: number;
};

export interface PathfinderSettings {
  allowDiagonal?: boolean;
  heuristicFilter?: Function;
}

export interface SceneSettings {
  element: HTMLElement;
  alpha: boolean;
  antialias: boolean;
  clearColor: string;
  sortObjects: boolean;
  fog: Fog;
  light: Light;
  lightPosition: Vector3;
  cameraType: string;
  cameraPosition: Vector3; // {x, y, z}
  orthoZoom: number;
}

export interface CameraControlSettings {
  minDistance: number;
  maxDistance: number;
  zoomSpeed: number;
  noZoom: boolean;
}

export interface GridJSONData {
  size: number;
  cellSize: number;
  cells: Cell[];
  extrudeSettings: ExtrudeSettings;
  autogenerated: boolean;
}

