import Cell from "./Cell";
import { ExtrudeSettings, TilemapSettings } from "../utils/Interfaces";
import { Shape, BufferGeometry, ShapeGeometry, Vector3, Group, Material } from "three";
import Tile from "./Tile";

export default interface Grid {
  type: string;
  size: number;
  cellSize: number;
  cells: { [key: string]: Cell };
  numCells: number;
  extrudeSettings: ExtrudeSettings;
  autogenerated: boolean;
  cellShape: Shape;
  cellGeo: BufferGeometry;
  cellShapeGeo: ShapeGeometry;

  cellToPixel(cell: Cell): Vector3;
  add(cell: Cell): Cell;
  remove(cell: Cell): void;
  cellToHash(cell: Cell): string;
  pixelToCell(pos: Vector3): Cell;
  dispose(): void;
  generateOverlay(size: number, overlayObj: Group, overlayMat: Material): void;
  generateTiles(tilemapSettings: TilemapSettings): Tile[];
  clearPath(): void;
  getNeighbors(cell: Cell, diagonals: boolean, heuristic: Function): Cell[];
  distance(cellA: Cell, cellB: Cell): number;
};